mappings:
  GridFieldCategorisationConfig: SilverStripe\Blog\Admin\GridFieldCategorisationConfig
  GridFieldFormAction: SilverStripe\Blog\Admin\GridFieldFormAction
  GridFieldMergeAction: SilverStripe\Blog\Admin\GridFieldMergeAction
  BlogCommentExtension: SilverStripe\Blog\Model\BlogCommentExtension
  BlogFilter: SilverStripe\Blog\Model\BlogFilter
  BlogFilter_GridField: SilverStripe\Blog\Model\BlogFilter_GridField
  BlogMemberExtension: SilverStripe\Blog\Model\BlogMemberExtension
  BlogPostFilter: SilverStripe\Blog\Model\BlogPostFilter
  BlogPostNotifications: SilverStripe\Blog\Model\BlogPostNotifications
  Blog: SilverStripe\Blog\Model\Blog
  Blog_Controller: SilverStripe\Blog\Controllers\BlogController
  BlogController: SilverStripe\Blog\Controllers\BlogController
  BlogCategory: SilverStripe\Blog\Model\BlogCategory
  BlogPost: SilverStripe\Blog\Model\BlogPost
  BlogPost_Controller: SilverStripe\Blog\Controllers\BlogPostController
  BlogPostController: SilverStripe\Blog\Controllers\BlogPostController
  BlogTag: SilverStripe\Blog\Model\BlogTag
  CategorisationObject: SilverStripe\Blog\Model\CategorisationObject
  BlogAdminSidebar: SilverStripe\Blog\Forms\BlogAdminSidebar
  GridFieldAddByDBField: SilverStripe\Blog\Forms\GridField\GridFieldAddByDBField
  GridFieldBlogPostState: SilverStripe\Blog\Forms\GridField\GridFieldBlogPostState
  GridFieldConfig_BlogPost: SilverStripe\Blog\Forms\GridField\GridFieldConfig_BlogPost
  BlogArchiveWidget: SilverStripe\Blog\Widgets\BlogArchiveWidget
  BlogCategoriesWidget: SilverStripe\Blog\Widgets\BlogCategoriesWidget
  BlogRecentPostsWidget: SilverStripe\Blog\Widgets\BlogRecentPostsWidget
  BlogTagsCloudWidget: SilverStripe\Blog\Widgets\BlogTagsCloudWidget
  BlogTagsWidget: SilverStripe\Blog\Widgets\BlogTagsWidget
